"""Claude: classify every Python module the Tag Team mod needs and write PYTHON_LEDGER.md (read-only static analysis)."""
import re
import json
from pathlib import Path
from collections import defaultdict

HERE = Path(__file__).resolve().parent
TOOLS = HERE / 'power-scale-trial/controller/game/tools'
EXTRA = [HERE / 'roster-tools', HERE]
mods = {}
for d in [TOOLS] + [p for p in EXTRA if p.is_dir()]:
    for f in sorted(d.glob('*.py')):
        if f.parent == HERE and not (f.name.startswith('codex_') or f.name in ('run_power_scale_native.py', 'native_rematch_trace.py')):
            continue
        key = f.name
        if key in mods and f.parent != TOOLS:
            key = 'roster-tools/' + key
        mods[key] = f


def classify(name, text):
    imports = set(re.findall(r'^\s*(?:import|from)\s+([A-Za-z_][\w]*)', text, re.M))
    lines = text.count('\n') + 1
    if name.startswith('codex_check') or name.startswith('test_') or '_check' in name:
        return 'test/dev'
    if 'PIL' in imports or 'fonts' in imports or 'extract_loading_assets' in name or 'pycdlib' in imports:
        if 'ingame_settings' in name or 'guest_loading' in name:
            return 'presentation (host-drawn)'
        return 'install-time tool (ISO/art/assets)'
    if 'Assembler(' in text:
        return 'guest-code generator'
    if re.search(r'\bpine\b', text) or 'native_preparation' in imports or 'PineClient' in text or re.search(r'class\s+(Worker|Session|StreamingSession)', text):
        return 'host orchestration (PINE)'
    if 'argparse' in imports and "__main__" in text and 'read_ram' in text:
        return 'offline builder CLI'
    return 'data/policy/tables'


rows = []
for name, f in mods.items():
    text = f.read_text(encoding='utf-8', errors='replace')
    rows.append(dict(name=name, lines=text.count('\n') + 1, kind=classify(name, text)))
by = defaultdict(list)
for r in rows:
    by[r['kind']].append(r)
dest = {
    'guest-code generator': 'frozen cave pack (build time) or native C++ feature; no Python at runtime',
    'host orchestration (PINE)': 'native C++ runtime lifecycle (M3); PINE only as a debug tool',
    'presentation (host-drawn)': 'native draw layer with baked glyph atlas (M5/M4)',
    'install-time tool (ISO/art/assets)': 'native installer step (C++/Kotlin) reading the user ISO; no Python on the user device',
    'offline builder CLI': 'build-time developer tooling (not shipped)',
    'data/policy/tables': 'port the tables to C++ or ship as versioned data files; generators read them at build time',
    'test/dev': 'developer only, never shipped',
}
out = ['# Python ledger: every Python module and where its job must end up', '',
       'Generated by `claude_python_ledger.py` (static heuristics over imports/constructs; reviewed by hand where noted). Written 2026-10-07.', '',
       'Goal (user): the Windows and Android installers must not depend on Python. Python may stay only as a developer/build tool.', '',
       '| Kind | Modules | Lines | Destination |', '| --- | ---: | ---: | --- |']
total_m = total_l = 0
for k in sorted(by, key=lambda k: -sum(r['lines'] for r in by[k])):
    m = len(by[k])
    l = sum(r['lines'] for r in by[k])
    total_m += m
    total_l += l
    out.append(f'| {k} | {m} | {l} | {dest[k]} |')
out.append(f'| **Total** | **{total_m}** | **{total_l}** | |')
out.append('')
for k in sorted(by, key=lambda k: -sum(r['lines'] for r in by[k])):
    out.append(f'## {k}')
    out.append('')
    out.append('Largest: ' + ', '.join(f"`{r['name']}` ({r['lines']})" for r in sorted(by[k], key=lambda r: -r['lines'])[:12]))
    out.append('')
(HERE / 'PYTHON_LEDGER.md').write_text('\n'.join(out) + '\n', encoding='utf-8')
(HERE / 'power-scale-trial' / 'python-ledger.json').write_text(json.dumps(rows, indent=1), encoding='utf-8')
print('\n'.join(out[:20]))
