"""Generate exact draw-program authentication for native presentation probes."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, sys.argv[2] if len(sys.argv)>2 else str(ROOT/'controller/tools'))
import beam_struggle, lockon_threat, lockon_select
import battle_mode_policy as policy


def main():
    target = Path(sys.argv[1])
    records = []
    for capacity in (3, 5):
        with policy.building_for(capacity):
            for kind, module, builder, base in (
                (1, beam_struggle, beam_struggle.draw_code, beam_struggle.DRAW),
                (2, lockon_threat, lockon_threat.draw_code, lockon_threat.DRAW),
                (3, lockon_select, lockon_select.marker_code, lockon_select.MARKER),
            ):
                records.append((kind, base, module.NATIVE_PROBE, builder()))
    records=list(dict.fromkeys(records))
    lines = ['// Generated by codex_v11_prompt_pack.py; full program authentication.']
    for index, (_, _, _, code) in enumerate(records):
        lines.append(f'inline constexpr uint8_t v11PromptBytes{index}[]={{'+','.join(map(str, code))+'};')
    lines += ['struct V11PromptGuard {uint32_t kind,base,probe;const uint8_t* bytes;size_t size;};',
              'inline constexpr V11PromptGuard v11PromptGuards[]={']
    for index, (kind, base, probe, code) in enumerate(records):
        lines.append(f'{{{kind}u,{base}u,{probe}u,v11PromptBytes{index},sizeof(v11PromptBytes{index})}},')
    lines.append('};')
    target.write_text('\n'.join(lines)+'\n', encoding='utf-8')
    print(f'PASS: {len(records)} v11 draw variants for both native capacities')


if __name__ == '__main__':
    main()
