"""Generate native UTF-8 tables from the complete EN/ES catalogue."""
import hashlib
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE / 'ui-assets/ui_strings.json'
TARGET = HERE / 'repo/ps2xRuntime/include/runtime/ps2_ui_strings.h'


def main():
    data = SOURCE.read_bytes()
    catalog = json.loads(data)
    if catalog['version'] != 1 or not catalog['strings']:
        raise ValueError('Unsupported or empty catalogue')
    strings = catalog['strings']
    for key, value in strings.items():
        if not re.fullmatch('[A-Za-z][A-Za-z0-9]*', key) or set(value) != {'en', 'es'}:
            raise ValueError(f'Incomplete locale/key: {key}')
        for text in value.values():
            if not isinstance(text, str) or not text or any(ord(c) < 32 for c in text):
                raise ValueError(f'Invalid label: {key}')
    # Escape UTF-8 bytes, so MSVC/Clang source encoding does not change assets.
    def literal(text):
        return '"' + ''.join(f'\\x{b:02x}' for b in text.encode('utf-8')) + '"'
    out = ['#pragma once', '// Generated by codex_build_ui_strings.py; edit ui-assets/ui_strings.json.',
           '// Source SHA256: ' + hashlib.sha256(data).hexdigest(),
           '#include <array>', '#include <cstddef>', '#include <cstdint>', '#include <string_view>',
           'namespace ps2x::ui {', 'enum class Language : uint8_t { English, Spanish };',
           'enum class TextId : uint16_t { ' + ', '.join(strings) + ', Count };',
           'inline constexpr std::array<std::array<std::string_view, 2>, ' + str(len(strings)) + '> kUiStrings{{']
    out += ['    {' + literal(v['en']) + ', ' + literal(v['es']) + '},' for v in strings.values()]
    out += ['}};', 'class Localizer {', '    Language language_ = Language::English;', 'public:',
            '    Language language() const { return language_; }',
            '    bool select(std::string_view tag) {',
            '        if (tag == "en" || tag == "en-US" || tag == "en-GB") language_ = Language::English;',
            '        else if (tag == "es" || tag == "es-ES" || tag == "es-CO" || tag == "es-MX") language_ = Language::Spanish;',
            '        else return false;', '        return true;', '    }',
            '    std::string_view tag() const { return language_ == Language::Spanish ? "es" : "en"; }',
            '    std::string_view text(TextId id) const {',
            '        auto key = static_cast<size_t>(id);',
            '        return key < kUiStrings.size() ? kUiStrings[key][language_ == Language::Spanish ? 1 : 0] : std::string_view{};',
            '    }', '};', '} // namespace ps2x::ui', '']
    TARGET.write_text('\n'.join(out), encoding='ascii')
    print('Generated', TARGET, 'labels:', len(strings), 'locales: en/es')


if __name__ == '__main__':
    main()
