"""Generate exact guest draw guards; retain wrapper/camera/gameplay work."""
from pathlib import Path
import sys, struct
HERE=Path(__file__).resolve().parent
sys.path.insert(0,str(HERE/'power-scale-trial/controller/game/tools'))
from codex_roster_overlay import install
install()
import viewport_hud as viewport, guest_killfeed as feed, fusion_duration as timer
import guest_healthbars as bars,display_settings as display,battle_mode_policy as policy
from prototype import Assembler

def main():
    records=[]
    for capacity in (3,5):
        with policy.building_for(capacity):
            for solo in (False,True):
                records.append((bars.DRAW,bars.DRAW,0,bars.draw_code(solo)))
                records.append((display.BAR_DRAW,display.BAR_DRAW,0,bars.draw_code(solo,visibility_filter=display.BAR_FILTER,entry=display.BAR_DRAW)))
    for legacy in (False,True):
        for styled in (False,True):
            for native in (False,True):
                for repaired in (False,True):
                    data=viewport.panel(legacy,styled,native,repaired=repaired)
                    records.append((viewport.PANEL,viewport.PANEL,0,data))
    for quad in (False,True):records.append((feed.DRAW,feed.DRAW,0,feed.draw_code(quad)))
    for compact in (False,True):
        address=feed.SMALL_TEXT if compact else feed.TEXT
        records.append((address,address,0,feed.text_code(compact)))
    # Execute the original save and chained render owner, then branch directly
    # to its original restore. Do not skip the viewport/scissor wrappers.
    original=Assembler.finish
    for previous in (feed.DRAW,0x07136000,viewport.CODE):
        for stacked in (False,True):
            for quad in (False,True):
                captured={}
                def finish(a):
                    if a.base==timer.DRAW:captured.update(a.labels)
                    return original(a)
                Assembler.finish=finish
                try:data=timer.draw(previous,stacked,quad)
                finally:Assembler.finish=original
                words=struct.unpack('<'+'I'*(len(data)//4),data)
                call=(3<<26)|(previous>>2)
                offset=words.index(call)*4+8
                records.append((timer.DRAW,timer.DRAW+offset,captured['done'],data))
    records=list(dict.fromkeys(records))
    output=['// Generated by codex_native_hud_draw_pack.py; exact live-byte guards.']
    for i,(_,_,_,data) in enumerate(records):
        output.append(f'inline constexpr uint8_t hudDrawBytes{i}[]={{'+','.join(str(x) for x in data)+'};')
    output.append('struct HudDrawGuard {uint32_t base,pc,next;const uint8_t* bytes;size_t size;};')
    output.append('inline constexpr HudDrawGuard hudDrawGuards[]={')
    for i,(base,pc,nextpc,data) in enumerate(records):output.append(f'{{{base}u,{pc}u,{nextpc}u,hudDrawBytes{i},sizeof(hudDrawBytes{i})}},')
    output.append('};')
    target=HERE/'repo/ps2xRuntime/include/runtime/ps2_ui_guest_draw_guards.inc'
    target.write_text('\n'.join(output)+'\n',encoding='utf-8')
    print(f'PASS {len(records)} exact draw variants; fusion chains and restore retained')
if __name__=='__main__':main()
